FROM alpine:latest AS base

RUN apk --no-cache update
RUN apk --no-cache add \
    gcc \
    g++ \
    gdb \
    make \
    cmake \
    git \
    github-cli \
    linux-headers \
    clang-extra-tools
